# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[0.3513, 0.6818, 0.1358, 0.2527, 0.3436, 0.7888, 0.9236],
        [0.8770, 0.9816, 0.1080, 0.6190, 0.1353, 0.2691, 0.9296],
        [0.9762, 0.2799, 0.0038, 0.6166, 0.1474, 0.5534, 0.5152],
        [0.1915, 0.3721, 0.2826, 0.0475, 0.8755, 0.6002, 0.2847],
        [0.0742, 0.9142, 0.0197, 0.4995, 0.1595, 0.2249, 0.3826],
        [0.7292, 0.1784, 0.6750, 0.4573, 0.3051, 0.8583, 0.8673],
        [0.3840, 0.8440, 0.0340, 0.9526, 0.6603, 0.7697, 0.0879]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor2 = torch.rand(1, 7)
tensor2

# Perform matrix multiplication
torch.mm(tensor, tensor2.T)

tensor([[1.7862],
        [1.6651],
        [1.1382],
        [1.3835],
        [1.3253],
        [1.9008],
        [1.9997]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
torch.mm(tensor, tensor2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
random_seed = 1234
torch.cuda.manual_seed(random_seed)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
tensor = torch.rand(2, 3).to('cuda')
tensor2 = torch.rand(2, 3).to('cuda')
tensor, tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
tensor = torch.mm(tensor, tensor2.T)

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
torch.max(tensor)

# Find min
torch.min(tensor)

tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
torch.argmax(tensor)

# Find arg min
torch.argmin(tensor)

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
random_seed = 7
torch.manual_seed(random_seed)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
torch.squeeze(tensor)

# Print out tensors and their shapes
tensor, tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))